img_size: [120,160]
top_cutoff: 40

# Sim
colors:
  RED:
    low_1: [0,140,100]
    high_1: [10,255,255]
    low_2: [165,140,100]
    high_2: [180,255,255]
  WHITE:
    #    low: [10,0,50]
    low: [0,0,50]
    #    low: [0,0,60]
    #    high: [180,255,255]
    high: [180,105,255]
#    high: [0, 0, 0]
  #    high: [180, 115, 255]
  #    high: [180,110,255]
  YELLOW:
    #    low: [15,120,85]
    low: [15,105,90]
    #    low: [15,100,80]
    #    high: [45,255,255]
    high: [30, 255, 245]
#    high: [30,255,255]

## Duckiebot
#colors:
#  RED:
#    low_1: [0,140,100]
#    high_1: [10,255,255]
#    low_2: [165,140,100]
#    high_2: [180,255,255]
#  WHITE:
##    low: [10,0,50]
#    low: [0,0,130]
##    high: [180,255,255]
#    high: [180,110,255]
##    high: [180,110,255]
#  YELLOW:
##    low: [15,120,85]
#    low: [15,150,120]
##    low: [15,100,80]
##    high: [45,255,255]
#    high: [50, 255, 245]
##    high: [40,255,255]

line_detector_parameters:
  canny_thresholds: [80,200]
  canny_aperture_size: 3
  dilation_kernel_size: 3
  hough_threshold: 2
  hough_min_line_length: 3
  hough_max_line_gap: 1


#img_size: [120,160]
#top_cutoff: 40
#
#colors:
#  RED:
#    low_1: [0,140,100]
#    high_1: [10,255,255]
#    low_2: [165,140,100]
#    high_2: [180,255,255]
#  WHITE:
#    low: [0,0,50]
#    high: [180,100,255]
#  YELLOW:
#    low: [10,100,100]
#    high: [45,255,255]
#
#line_detector_parameters:
#  canny_thresholds: [80,200]
#  canny_aperture_size: 3
#  dilation_kernel_size: 3
#  hough_threshold: 2
#  hough_min_line_length: 3
#  hough_max_line_gap: 1

### Default values from dt-core
#img_size: [120,160]
#top_cutoff: 40
#
#colors:
#  RED:
#    low_1: [0,140,100]
#    high_1: [15,255,255]
#    low_2: [165,140,100]
#    high_2: [180,255,255]
#  WHITE:
#    low: [0,0,150]
#    high: [180,100,255]
#  YELLOW:
#    low: [25,140,100]
#    high: [45,255,255]
#
#line_detector_parameters:
#  canny_thresholds: [80,200]
#  canny_aperture_size: 3
#  dilation_kernel_size: 3
#  hough_threshold: 2
#  hough_min_line_length: 3
#  hough_max_line_gap: 1